//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnExam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnExam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to close the exam. Continue?.
        /// </summary>
        internal static string aboutToClose {
            get {
                return ResourceManager.GetString("aboutToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to start the exam. Continue?.
        /// </summary>
        internal static string aboutToStart {
            get {
                return ResourceManager.GetString("aboutToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be saved and locked. Activate exam?.
        /// </summary>
        internal static string activateExam {
            get {
                return ResourceManager.GetString("activateExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer .
        /// </summary>
        internal static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string areYouSure {
            get {
                return ResourceManager.GetString("areYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available!.
        /// </summary>
        internal static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Exam.
        /// </summary>
        internal static string btnCloseExam {
            get {
                return ResourceManager.GetString("btnCloseExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Results.
        /// </summary>
        internal static string btnViewResults {
            get {
                return ResourceManager.GetString("btnViewResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be empty!.
        /// </summary>
        internal static string cantBeEmpty {
            get {
                return ResourceManager.GetString("cantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t sign up!.
        /// </summary>
        internal static string cantSignUp {
            get {
                return ResourceManager.GetString("cantSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t update!.
        /// </summary>
        internal static string cantUpdate {
            get {
                return ResourceManager.GetString("cantUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open sessions will still work but entries will be disabled. Close exam?.
        /// </summary>
        internal static string closeExam {
            get {
                return ResourceManager.GetString("closeExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully!.
        /// </summary>
        internal static string deleteSuccess {
            get {
                return ResourceManager.GetString("deleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error!.
        /// </summary>
        internal static string errorDB {
            get {
                return ResourceManager.GetString("errorDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already a user with this email!.
        /// </summary>
        internal static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message: .
        /// </summary>
        internal static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete an exam already done..
        /// </summary>
        internal static string examAlreadyDone {
            get {
                return ResourceManager.GetString("examAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all fields!.
        /// </summary>
        internal static string fillFields {
            get {
                return ResourceManager.GetString("fillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid exam!.
        /// </summary>
        internal static string invalidExam {
            get {
                return ResourceManager.GetString("invalidExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login!.
        /// </summary>
        internal static string invalidLogin {
            get {
                return ResourceManager.GetString("invalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name, it already exists..
        /// </summary>
        internal static string invalidName {
            get {
                return ResourceManager.GetString("invalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username!.
        /// </summary>
        internal static string invalidUsername {
            get {
                return ResourceManager.GetString("invalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid duration value!.
        /// </summary>
        internal static string invalidValue {
            get {
                return ResourceManager.GetString("invalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match!.
        /// </summary>
        internal static string noMatch {
            get {
                return ResourceManager.GetString("noMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select only one exam..
        /// </summary>
        internal static string oneExamOnly {
            get {
                return ResourceManager.GetString("oneExamOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option .
        /// </summary>
        internal static string option {
            get {
                return ResourceManager.GetString("option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be lost. Do you still wish to close?.
        /// </summary>
        internal static string saveError {
            get {
                return ResourceManager.GetString("saveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved sucessfully!.
        /// </summary>
        internal static string saveSuccess {
            get {
                return ResourceManager.GetString("saveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected rows!.
        /// </summary>
        internal static string selectedRows {
            get {
                return ResourceManager.GetString("selectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving, contact your evaluator..
        /// </summary>
        internal static string sessionSaveError {
            get {
                return ResourceManager.GetString("sessionSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable!.
        /// </summary>
        internal static string unavailable {
            get {
                return ResourceManager.GetString("unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re about to delete this exam. Continue?.
        /// </summary>
        internal static string verifyDelete {
            get {
                return ResourceManager.GetString("verifyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying....
        /// </summary>
        internal static string verifying {
            get {
                return ResourceManager.GetString("verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start exam?.
        /// </summary>
        internal static string verifyStart {
            get {
                return ResourceManager.GetString("verifyStart", resourceCulture);
            }
        }
    }
}
